name: NEW Build DS920+ 7.1.1-42962

on:
#  schedule:
#    - cron: '0 18 * * *'
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: DS920+
            version: 7.1.1-42962

    steps:
      - name: 检出项目文件
        uses: actions/checkout@v3
        
      - name: 获取当前时间
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
        
      - name: 获取项目描述
        id: desc
        run: |
          wget https://raw.githubusercontent.com/Mr-jiangrj/Redpill_Build/main/README.MD -O /home/runner/desc.txt
          echo "::set-output name=description::$(cat /home/runner/desc.txt)"
        
      - name: 环境准备
        run: |
          sudo apt update
          sudo apt-get install -y curl bspatch jq git
          git clone https://github.com/jumkey/redpill-load.git /home/runner/redpill-load
          wget https://raw.githubusercontent.com/Mr-jiangrj/Redpill_Build/main/ds920p_user_config.json -O /home/runner/redpill-load/ds920p_user_config.json
          wget https://raw.githubusercontent.com/pocopico/rp-ext/main/redpill/releases/redpill-4.4.180plus-geminilake.tgz
          tar zxvf redpill-4.4.180plus-geminilake.tgz -C ./
          mv ./redpill.ko /home/runner/redpill-load/ext/rp-lkm/redpill-linux-v4.4.180+.ko
          
      - name: 添加扩展驱动
        run: |
          cd /home/runner/redpill-load 
          ./ext-manager.sh add 'https://raw.githubusercontent.com/pocopico/rp-ext/master/vmxnet3/rpext-index.json'
          ./ext-manager.sh add 'https://raw.githubusercontent.com/pocopico/redpill-load/develop/redpill-acpid/rpext-index.json'
          
      - name: 编译引导
        run: |
          cd /home/runner/redpill-load
          sed -i 's#https://github.com/jumkey/redpill-load/raw/develop/redpill-boot-wait/rpext-index.json#https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json#g' ./bundled-exts.json
          sed -i 's#https://github.com/jumkey/redpill-load/raw/develop/redpill-virtio/rpext-index.json#https://raw.githubusercontent.com/pocopico/redpill-load/develop/redpill-virtio/rpext-index.json#g' ./bundled-exts.json
          mkdir -p ./config/DS920+/7.1.1-42962
          cp -r ./config/DS920+/7.0.1-42218/config.json ./config/DS920+/7.1.1-42962/config.json
          cp -r ./config/DS920+/7.0.1-42218/zImage-001-920p-42218-ramdisk-and-flag-NOP.bsp ./config/DS920+/7.1.1-42962/zImage-001-920p-42218-ramdisk-and-flag-NOP.bsp
          sed -i 's/ds920p_42218/ds920p_42962/g' ./config/DS920+/7.1.1-42962/config.json
          sed -i 's#https://global.download.synology.com/download/DSM/release/7.0.1/42218/DSM_DS920%2B_42218.pat#https://ghproxy.com/https://github.com/Mr-jiangrj/Redpill_Build/releases/download/PAT/DSM_DS920+_42962_Update1.pat#g' ./config/DS920+/7.1.1-42962/config.json
          sed -i 's/fe2a4648f76adeb65c3230632503ea36bbac64ee88b459eb9bfb5f3b8c8cebb3/9f3f3d5b9600d033b53c78e945cf5bcce14a09efcc500ea27e0df55819903437/g' ./config/DS920+/7.1.1-42962/config.json
          sed -i 's/346b68f662b50f47d3ee6c2bc9de6302e4b60436142c24ee88b620c7afd1ba06/2de065851b8d3a222db1feea696aab12ded7b582876b22ff6e847cd6f2e62ecf/g' ./config/DS920+/7.1.1-42962/config.json
          sed -i 's/f7dd1317f24ec6b9bac839e37f66b59030218c7f97c06f73f1f54ed0f892c4aa/043d784fd35ee57eb5279c94a65e66ff2c7c4229728818bc141927a6451e95ee/g' ./config/DS920+/7.1.1-42962/config.json
          sudo BRP_JUN_MOD=1 BRP_DEBUG=1 BRP_USER_CFG=ds920p_user_config.json ./build-loader.sh '${{matrix.platform}}' '${{matrix.version}}'
          
      - name: 上传引导镜像到 Github Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Redpill-load
          name: ${{matrix.version}} Build ${{steps.date.outputs.today}}
          body: ${{steps.desc.outputs.description}}
          draft: false
          prerelease: false
          files: |
            /home/runner/redpill-load/images/*.img
            
#      - name: 删除旧的 Release 项目
#        uses: dev-drprasad/delete-older-releases@v0.2.0
#        with:
#          repo: Mr-jiangrj/Redpill_Build
#          keep_latest: 1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
#      - name: 上传引导镜像到 Github Actions
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{matrix.platform}} ${{matrix.version}}
#          path: /home/runner/redpill-load/images/*.img
#          if-no-files-found: error
